defaults:
  - base
  - model: gpflow_gpr

dataloader:
  _target_: docs.diffusion_processes.exp_dp_utils.load_apple_stock_exp_data
  data_path: ${data_path}

wandb:
  username: null
  tags: ["GPR", "Apple Stock"]

data_path: ???

optimize: true
lr: 0.1
max_itr: 10000
optim_tol: 1e-4
constant_kernel_variance : 1
linear_kernel_variance : 1
matern_lengthscale: 1
