defaults:
  - vi_base
  - prior_sde: mlpdrift

dataloader:
  _target_: docs.diffusion_processes.exp_dp_utils.load_gps_exp_data
  data_path: ${data_path}
  train_dim: ???

trainer:
  _target_: docs.diffusion_processes.vi_markov_gp_trainer.VIMarkovGPTrainer
  _partial_: true
  q_lr: 0.1
  x0_lr: 0.1
  max_itr: 1000
  learn_prior_sde: true
  warmup_x0_itr: 10
  optim_tol: 1e-2
  optimize_prior_initial_state: true
  prior_sde_lr: 1e-2

wandb:
  tags: ["VDP", "GPS"]

prior_x0_mean: 0
prior_x0_cov: 0.1

cvi_posterior_path: null
vi_model_path: null
